name: blogapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^2.0.3
  translator: ^0.1.2
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0

  logger: ^0.9.1
  flutter_facebook_login: ^3.0.0
  flutter_secure_storage: ^3.3.3
  image_picker: ^0.6.7+4
  json_annotation:
  dio: ^3.0.10
  geocoding: any
  fluttertoast:
  url_launcher: ^5.4.1
  font_awesome_flutter: ^9.2.0
  charts_flutter: ^0.7.0
  flutter_widget_from_html_core: ^0.2.0
  flutter_carousel_slider: ^1.0.1
  carousel_slider: ^3.0.0
  flutter_icons: ^1.1.0
  webview_flutter: ^2.0.12
  google_maps_flutter: ^0.5.32
  share: ^2.0.4
  animated_text_kit:
  community_material_icon: ^5.4.55
  shared_preferences:
  syncfusion_flutter_pdf: ^18.4.47-beta
  path_provider: ^1.6.28
  open_file: ^3.1.0
  introduction_screen: ^1.0.9
  flutter_svg: ^0.19.1
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4
  universal_html: ^1.2.4
  change_app_package_name: ^1.0.0
  showcaseview: ^0.1.6
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^1.4.4+1
  animated_splash_screen: ^1.2.0

  email_auth:
  firebase_core:
  firebase_messaging:
  localization: ^2.1.0
  flutter_spinkit: ^5.1.0
  photo_view: ^0.13.0
  like_button: ^2.0.4
  stripe_payment: ^1.0.6
  flutter_typeahead:
  file_picker: ^1.4.3+2
  firebase_ml_vision: ^0.11.0
  sqflite: ^2.0.0+4
  loading_animations: ^2.1.0
  provider: ^6.0.1
  flutter_easyloading: ^3.0.5
  favorite_button: ^0.0.4
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  intl:
  curved_navigation_bar: ^1.0.1
  sound_stream: ^0.2.0
  rxdart: ^0.27.1
  http: ^0.12.2
  syncfusion_flutter_calendar:
  awesome_dialog:
  flutter_slidable:
  flutter_credit_card: ^3.0.2
  invoiceninja:
  auto_size_text: ^3.0.0
  syncfusion_flutter_charts:
  json_table: ^2.0.1

  extended_image:
  oktoast: ^3.1.5
  image_size_getter: ^2.1.2
  hexcolor:































dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo1.png
    - assets/wel.png
    - assets/login.jpg
    - assets/welcome.jpg
    - assets/leaf.png
    - assets/leaf2.png
    - assets/govipiyasa_logo.png
    - assets/profile.png
    - assets/shop.jpg
    - assets/architect.jpg
    - assets/forum.png
    - assets/garden.png
    - assets/expert.png
    - assets/about.jpg
    - assets/glossy-e-commerce.png
    - assets/splash_2.png
    - assets/splash_3.png
    - assets/splash_1.png
    - assets/3.png
    - assets/plants1.jpg
    - assets/fertilizer.jpg
    - assets/card_provider/
    - assets/main.png
    - assets/placeholder.png
    - assets/expertform.png
    - assets/flowers2.png
    - assets/flowers3.jpg
    - assets/email2.png
    - assets/loginimg.jpg
    - assets/loginimg3.jpg
    - assets/loginimg2.png
    - assets/Delivery.png
    - assets/onion.jpg
    - assets/rice.jpg
    - assets/fruits.jpg
    - assets/vegetables.jpg
    - assets/31.png
    - assets/32.png
    - assets/robot.png
    - assets/robot.jpg
    - assets/camera.png
    - assets/default.jpg
    - assets/govipiyasa.json
    - assets/Garden1.jpg
    - assets/canvas.png
    - assets/master.png
    - assets/QnA.jpg
    - assets/expert.jpg
    - assets/item5.jpg
    - assets/shopping_cart.png
    - assets/policy/policy.txt
    - assets/bankcard.jpg
    - assets/board1.jpg
    - assets/board2.jpg
    - assets/board3.jpg
    - assets/splashscreen.jpg
    - assets/bankimg.jpg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Indies
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/icon/MyFlutterApp.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Roboto
      fonts:
        - asset: fonts/RobotoSlab-Black.ttf
        - asset: fonts/RobotoSlab-Light.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
